-- Custom domain verification (backend-maturity skeleton; the feature is shown
-- as "coming soon" in the UI - no real Vercel domain attachment happens).
-- A PENDING row is verified by an async @Scheduled job that resolves the
-- domain's TXT record and matches the verification token.
CREATE TABLE custom_domains (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_kit_id       BIGINT NOT NULL REFERENCES media_kits(id) ON DELETE CASCADE,
    domain             VARCHAR(255) NOT NULL UNIQUE,
    verification_token VARCHAR(255) NOT NULL,
    status             VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    attempts           INT          NOT NULL DEFAULT 0,
    last_checked_at    TIMESTAMP(6),
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_custom_domains_status ON custom_domains (status, last_checked_at);
CREATE INDEX idx_custom_domains_kit ON custom_domains (media_kit_id);
