-- Rate card: what the creator charges per deliverable (the single thing brands
-- look for first in a media kit). display_order is the owner-chosen position;
-- the list is frozen into the publish snapshot like collaborations, so draft
-- price edits never move a published page.
CREATE TABLE rate_card_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_kit_id  BIGINT NOT NULL REFERENCES media_kits(id) ON DELETE CASCADE,
    service_name  VARCHAR(255) NOT NULL,
    price_amount  NUMERIC(12,2) NOT NULL,
    currency      VARCHAR(3) NOT NULL DEFAULT 'TRY',
    note          VARCHAR(500),
    display_order INT NOT NULL DEFAULT 0
);

CREATE INDEX idx_rate_card_items_kit ON rate_card_items (media_kit_id, display_order);
