-- Brand contact requests submitted from the public page. Ingestion mirrors the
-- view beacon's anti-abuse model: bot filter, honeypot, and a per-visitor
-- window cap keyed on the anonymous daily-rotating fingerprint (raw IP is
-- never stored). Every submission answers 202 regardless of outcome, so the
-- endpoint leaks nothing about which slugs exist or which kits accept contact.
CREATE TABLE kit_leads (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_kit_id  BIGINT NOT NULL REFERENCES media_kits(id) ON DELETE CASCADE,
    brand_name    VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    message       VARCHAR(2000) NOT NULL,
    status        VARCHAR(16) NOT NULL DEFAULT 'NEW',
    visitor_hash  VARCHAR(64) NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_kit_leads_kit_created ON kit_leads (media_kit_id, created_at);
CREATE INDEX idx_kit_leads_dedup ON kit_leads (media_kit_id, visitor_hash, created_at);

-- Ingestion kill switch: disabling takes effect immediately (submissions are
-- dropped), while the form itself disappears from the public page only on the
-- next publish (frozen-snapshot rule).
ALTER TABLE media_kits ADD COLUMN contact_enabled BOOLEAN NOT NULL DEFAULT TRUE;
