-- External stat sources (YouTube Data API, more later). One source per
-- platform per kit; the scheduled sync job APPENDS fetched measurements to the
-- existing platform_stats time series - the append-only model gets real data.
-- last_synced_at tracks the last SUCCESS; failures only fill last_error, so a
-- broken source keeps being retried on the normal cadence.
CREATE TABLE stats_sources (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_kit_id   BIGINT NOT NULL REFERENCES media_kits(id) ON DELETE CASCADE,
    platform       VARCHAR(16) NOT NULL,
    external_id    VARCHAR(255) NOT NULL,
    enabled        BOOLEAN NOT NULL DEFAULT TRUE,
    last_synced_at TIMESTAMP(6),
    last_error     VARCHAR(500),
    created_at     TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_stats_sources_kit_platform UNIQUE (media_kit_id, platform)
);

CREATE INDEX idx_stats_sources_due ON stats_sources (enabled, last_synced_at);
