-- Outbox for "a brand contacted you" emails.
--
-- A row is written in the SAME transaction as the lead it belongs to, and a
-- scheduled job delivers it afterwards. That ordering is the point: the mail
-- provider is never touched while the brand's submission is being handled, so
-- an outage there cannot slow down, fail, or lose a lead. The worst it can do
-- is leave rows here in PENDING until it recovers.
--
-- recipient_email is snapshotted rather than joined at send time: the message
-- should go to the address the owner had when the lead arrived, even if they
-- change it (or delete the account) before the queue drains.
CREATE TABLE lead_notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id         BIGINT NOT NULL REFERENCES kit_leads(id) ON DELETE CASCADE,
    recipient_email VARCHAR(255) NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempts        INT          NOT NULL DEFAULT 0,
    last_error      VARCHAR(500),
    next_attempt_at TIMESTAMP(6) NOT NULL,
    sent_at         TIMESTAMP(6),
    created_at      TIMESTAMP(6) NOT NULL
);

-- The job's only query: due work, oldest first.
CREATE INDEX idx_lead_notifications_due ON lead_notifications (status, next_attempt_at);

-- Backs the per-owner hourly cap, so one kit going viral (or being hammered)
-- cannot turn into a mailbox flood.
CREATE INDEX idx_lead_notifications_recipient ON lead_notifications (recipient_email, created_at);

-- Per-account switch for these emails. Default TRUE: someone who publishes a
-- contact form is asking to be contacted.
ALTER TABLE users ADD COLUMN lead_notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE;
