-- Daily rollup of page_views, so raw view rows can be pruned without changing
-- the numbers a creator sees.
--
-- page_views is append-only and had no retention at all: it grows with traffic
-- forever, on a free Postgres tier, holding per-visit rows long after anyone
-- would act on them. Deleting old rows naively was not an option either --
-- total views and unique visitors are counted over the whole table, so pruning
-- would have silently walked a creator's lifetime numbers backwards.
--
-- This table is what makes pruning safe. The retention job folds each day into
-- one row before deleting the raw rows behind it, and the totals are read as
-- rollup + whatever is still inside the retention window.
--
-- The unique count survives exactly, not approximately, and that is a property
-- of the fingerprint rather than luck: visitor_hash includes the day, so it
-- rotates at midnight and the same person is already a different hash tomorrow.
-- "Distinct visitors all time" was therefore always the sum of the daily
-- distinct counts, which is precisely what this table stores.
CREATE TABLE page_view_daily (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_kit_id    BIGINT NOT NULL REFERENCES media_kits(id) ON DELETE CASCADE,
    -- "view_day" rather than "day": day is a keyword in enough dialects to be
    -- worth not finding out which ones the hard way.
    view_day        DATE   NOT NULL,
    views           BIGINT NOT NULL,
    unique_visitors BIGINT NOT NULL,
    CONSTRAINT uq_page_view_daily UNIQUE (media_kit_id, view_day)
);

CREATE INDEX idx_page_view_daily_kit ON page_view_daily (media_kit_id);

-- The retention scan reads by age across all kits, which the existing
-- (media_kit_id, viewed_at) index cannot serve.
CREATE INDEX idx_page_views_viewed_at ON page_views (viewed_at);
