-- Per-recipient share links, so a creator can tell WHO looked rather than only
-- how many did.
--
-- The product's premise is that sending a brand a link and seeing them read it
-- is the point. Analytics could only ever answer "three views" because every
-- visitor is an anonymous daily-rotating hash -- deliberately, and that stays
-- true. This adds the missing half from the other end: the creator labels the
-- link before sending it, so the attribution comes from what they already know
-- rather than from anything learned about the visitor.
--
-- The token is NOT access control. The published page is public either way, and
-- a link with no token still works exactly as before; this only decides which
-- column a view is counted in. Treating it as a secret would invite the opposite
-- mistake -- gating content on a value that ends up in browser history, chat
-- logs and referrer headers.
CREATE TABLE kit_share_links (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_kit_id BIGINT       NOT NULL REFERENCES media_kits(id) ON DELETE CASCADE,
    -- Random and unique across every kit: the beacon carries only the token, so
    -- it has to identify the link on its own.
    token        VARCHAR(32)  NOT NULL,
    -- What the creator called it. "Nike", "Ajans - 3. tur".
    label        VARCHAR(120) NOT NULL,
    -- Revoked rather than deleted: deleting would silently reassign the views
    -- already attributed to it, and "we stopped sharing this in March" is
    -- history worth keeping.
    revoked_at   TIMESTAMP(6),
    created_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_kit_share_links_token UNIQUE (token)
);

CREATE INDEX idx_kit_share_links_kit ON kit_share_links (media_kit_id);

-- Attribution lives on the view, not on the link, so a link's counters are
-- derived rather than stored: no counter to drift, and the daily series and
-- the per-link series come from the same rows.
--
-- Nullable and ON DELETE SET NULL: a view whose link was hard-deleted is still
-- a real view. Losing the attribution is acceptable, losing the visit is not.
ALTER TABLE page_views
    ADD COLUMN share_link_id BIGINT REFERENCES kit_share_links(id) ON DELETE SET NULL;

CREATE INDEX idx_page_views_share_link ON page_views (share_link_id, viewed_at);
