-- Showcase content: the creator's best posts and videos.
--
-- A media kit with no media in it was the product's most conspicuous gap. A
-- brand deciding whether to work with someone wants to see the work, and the
-- page could show follower counts, audience splits and prices but not a single
-- thing the creator had actually made.
--
-- Links and thumbnails rather than uploads, for the same reason the avatar is a
-- URL: the host's disk is wiped on every deploy, so an upload endpoint would
-- mean either a paid object store or a feature that silently loses files. The
-- content already lives on the platform it was published to, which is also
-- where a brand would rather watch it.
CREATE TABLE kit_media_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_kit_id  BIGINT       NOT NULL REFERENCES media_kits(id) ON DELETE CASCADE,
    title         VARCHAR(255) NOT NULL,
    -- Where the piece lives. HTTPS-only, the same rule every other URL column
    -- in this schema uses.
    url           VARCHAR(1000) NOT NULL,
    -- Optional preview image. Absent is fine and renders as a titled card:
    -- a creator should not have to hunt for a thumbnail URL to list their work.
    thumbnail_url VARCHAR(1000),
    -- Which platform it is on, for the badge. Free text rather than the Platform
    -- enum on purpose: this is a label on a link, not a source of measurements,
    -- and constraining it would mean a creator cannot list a piece that lives
    -- somewhere the stats pipeline does not support.
    platform      VARCHAR(20),
    note          VARCHAR(500),
    display_order INT          NOT NULL DEFAULT 0,
    created_at    TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_kit_media_items_kit ON kit_media_items (media_kit_id, display_order);
