-- Forgotten-password recovery.
--
-- The README listed this as a known limitation for a reason: there was no way
-- to send mail, so there was no way to prove someone owns an address, so an
-- account whose password was lost was lost with it. The outbox added for lead
-- notifications made the missing half possible.
--
-- WHY THERE IS NO DELIVERY STATE HERE, unlike lead_notifications.
--
-- Those two requirements cannot both hold: store only a hash of the token, and
-- send the mail later from a background job. The job would need the plaintext,
-- and the whole point of the hash is that the database does not have it.
--
-- The outbox exists because a lost in-flight send loses a LEAD -- valuable and
-- unrecoverable. A lost reset mail is neither: the person clicks the button
-- again. So this follows the publish path's rule instead -- commit, then make
-- the network call, never hold a transaction open across it -- and keeps the
-- hash. A failed send is counted and logged, and costs one retry by a human.
CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- The hash, never the token. A database leak must not hand somebody a
    -- working reset link for every account that recently used this flow.
    token_hash VARCHAR(64)  NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    -- Single use. Set on the reset that consumed it, and on every other
    -- outstanding token for that user at the same moment.
    used_at    TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_password_reset_token_hash UNIQUE (token_hash)
);

-- Invalidating a user's other tokens, and the per-account hourly cap.
CREATE INDEX idx_password_reset_user ON password_reset_tokens (user_id, created_at);
