-- Outbox for the "choose a new password" email.
--
-- The lead outbox (V19) exists so a mail outage cannot cost a creator a brand's
-- message. This one exists for a different reason, and it is worth writing down
-- because it changes the shape of the table.
--
-- The reset mail used to be sent inside the request that asked for it. That made
-- the endpoint measurably slower for an address that has an account than for one
-- that does not -- roughly 0.2s against 1.5s against a real provider -- which is
-- an account-existence oracle for anyone holding a list of addresses, and the
-- exact thing this flow promises not to be. Queueing makes every request do the
-- same cheap work and return at the same speed.
--
-- WHAT IS DELIBERATELY NOT IN THIS TABLE: the token.
--
-- password_reset_tokens stores a hash precisely so a database leak does not hand
-- somebody a working link. An outbox row carrying the plaintext (or a rendered
-- body containing it) would give that back, and would do it for longest exactly
-- when the queue is backed up. So a row points at the token instead, and the
-- dispatcher rotates that token when it sends: new secret, new hash, new expiry.
--
-- The rotation also fixes a problem the obvious design has. A stored token would
-- keep its original 30 minutes while the retries walk 1, 5 and 25 minutes, so
-- the last attempt would deliver a link that is already dead -- worse than
-- sending nothing, because it looks like the product is broken. Minting at send
-- time means the 30 minutes always starts when the mail actually leaves.
--
-- One row in password_reset_tokens per request, rotated in place rather than
-- replaced, so retries cannot inflate the per-account hourly cap and lock
-- somebody out of requesting a reset at the moment mail is failing them.
CREATE TABLE password_reset_notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id        BIGINT NOT NULL REFERENCES password_reset_tokens(id) ON DELETE CASCADE,
    recipient_email VARCHAR(255) NOT NULL,
    locale          VARCHAR(10)  NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempts        INT          NOT NULL DEFAULT 0,
    last_error      VARCHAR(500),
    next_attempt_at TIMESTAMP(6) NOT NULL,
    sent_at         TIMESTAMP(6),
    created_at      TIMESTAMP(6) NOT NULL
);

-- The job's only query: due work, oldest first.
CREATE INDEX idx_password_reset_notifications_due
    ON password_reset_notifications (status, next_attempt_at);
