-- Application users. Passwords are stored only as BCrypt hashes.
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(255) NOT NULL,
    plan          VARCHAR(50)  NOT NULL DEFAULT 'FREE',
    created_at    TIMESTAMP(6) NOT NULL
);
