-- Failed unlock attempts on password-protected kits, moved out of memory.
--
-- The counter was a Caffeine cache keyed by slug + client IP. On one instance
-- that is a working brute-force guard. On two it becomes a guard that permits
-- five wrong guesses per instance per window, and the attacker does not have
-- to know that to benefit from it -- ordinary load balancing hands them the
-- extra budget for free. The limit silently becomes 5 x N.
--
-- One row per failed attempt, so the window stays sliding, exactly as the
-- in-memory version was. Five rows per key at most before the guard trips, and
-- a successful unlock deletes them.
CREATE TABLE kit_unlock_failures (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_key VARCHAR(255) NOT NULL,
    failed_at   TIMESTAMP(6) NOT NULL
);

-- Both reads are "this key, inside the window", and the sweep is "anything
-- outside it". Leading with attempt_key serves the first two; failed_at alone
-- serves the sweep.
CREATE INDEX idx_kit_unlock_failures_key ON kit_unlock_failures (attempt_key, failed_at);
CREATE INDEX idx_kit_unlock_failures_age ON kit_unlock_failures (failed_at);
