-- Verifying that somebody can actually receive mail at the address they are
-- moving their account to.
--
-- Until now the change applied the moment the current password checked out.
-- That password is the control that matters and it is not being removed: it is
-- what stops a session somebody walked away from being used to move the
-- account to an attacker's address, and a link sent to the new address would
-- not stop that. What the password cannot catch is a typo, and the cost of a
-- typo here is the whole account -- the address is the login, so the owner is
-- locked out of an account that now belongs to an address nobody reads.
--
-- WHY ONE TABLE, when password reset uses two.
--
-- There the split is load-bearing: the outbox must not carry the token,
-- because password_reset_tokens stores a hash precisely so a leak does not
-- hand somebody a working link. That reasoning is about the plaintext, not the
-- hash, and this table stores a hash too and rotates it per delivery attempt
-- for the same reason -- so the secret is never at rest here either. What the
-- split also buys there is an account-existence guarantee: a reset must answer
-- identically for an address that has an account and one that does not. This
-- flow has no such promise to keep. It is authenticated, one row per request,
-- and the requester already knows the account exists because they just typed
-- its password.
CREATE TABLE email_change_requests (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- Where the account is moving. Not applied to users.email until the link
    -- in the mail sent here is opened.
    new_email       VARCHAR(255) NOT NULL,
    -- sha256 of the token that was mailed, rotated on each delivery attempt so
    -- a retried mail never carries a link that expired while it queued.
    token_hash      VARCHAR(64)  NOT NULL,
    expires_at      TIMESTAMP(6) NOT NULL,
    used_at         TIMESTAMP(6),
    locale          VARCHAR(10)  NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempts        INT          NOT NULL DEFAULT 0,
    last_error      VARCHAR(500),
    next_attempt_at TIMESTAMP(6) NOT NULL,
    sent_at         TIMESTAMP(6),
    created_at      TIMESTAMP(6) NOT NULL
);

-- The dispatcher's only query: due work, oldest first.
CREATE INDEX idx_email_change_requests_due
    ON email_change_requests (status, next_attempt_at);

-- Redeeming a link is a lookup by hash.
CREATE UNIQUE INDEX idx_email_change_requests_token
    ON email_change_requests (token_hash);

-- Superseding an account's earlier pending requests when a new one is made.
CREATE INDEX idx_email_change_requests_user
    ON email_change_requests (user_id, used_at);
