-- Authored media kit (draft owned by a user). The public snapshot lives in the
-- separate 'kits' table; publishing (a later step) renders a media kit into it.
CREATE TABLE media_kits (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    slug       VARCHAR(255) NOT NULL UNIQUE,
    title      VARCHAR(255) NOT NULL,
    headline   VARCHAR(500),
    avatar_url VARCHAR(1000),
    theme      VARCHAR(50)  NOT NULL DEFAULT 'light',
    status     VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_media_kits_user_id ON media_kits (user_id);
