-- Immutable publish snapshots. Publishing copies the draft into content_json;
-- the public page is only ever served from the ACTIVE version (the one
-- media_kits.published_version_id points at), never from the draft.
CREATE TABLE media_kit_versions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_kit_id   BIGINT NOT NULL REFERENCES media_kits(id) ON DELETE CASCADE,
    version_number INT NOT NULL,
    -- Slug at publish time, denormalized out of content_json so the public
    -- lookup (and cross-kit slug collision checks) can be indexed.
    slug           VARCHAR(255) NOT NULL,
    content_json   TEXT NOT NULL,
    published_at   TIMESTAMP(6) NOT NULL,
    UNIQUE (media_kit_id, version_number)
);

CREATE INDEX idx_media_kit_versions_slug ON media_kit_versions (slug);

ALTER TABLE media_kits
    ADD COLUMN published_version_id BIGINT REFERENCES media_kit_versions(id);

-- Migrate the demo page into the real model. The owner is a system account
-- that can never log in ('*DISABLED*' is not a valid BCrypt hash, so password
-- checks always fail). 'demo' is a reserved slug, so no user can claim it.
INSERT INTO users (email, password_hash, display_name, plan, created_at)
VALUES ('demo@localmediakit.local', '*DISABLED*', 'LocalMediaKit', 'FREE', CURRENT_TIMESTAMP);

INSERT INTO media_kits (user_id, slug, title, headline, avatar_url, theme, status, created_at, updated_at)
SELECT id, 'demo', 'Demo Medya Kiti',
       'LocalMediaKit ile yayinlanan ornek medya kiti', NULL, 'light', 'PUBLISHED',
       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM users WHERE email = 'demo@localmediakit.local';

INSERT INTO media_kit_versions (media_kit_id, version_number, slug, content_json, published_at)
SELECT id, 1, 'demo',
       '{"slug":"demo","title":"Demo Medya Kiti","headline":"LocalMediaKit ile yayinlanan ornek medya kiti","avatarUrl":null,"theme":"light","displayName":"LocalMediaKit"}',
       CURRENT_TIMESTAMP
FROM media_kits WHERE slug = 'demo';

UPDATE media_kits
SET published_version_id = (SELECT id FROM media_kit_versions
                            WHERE slug = 'demo' AND version_number = 1)
WHERE slug = 'demo';

-- The Step 0 proof table is superseded: public reads now come from
-- media_kit_versions and publishing goes through the authenticated flow.
DROP TABLE kits;
