-- Platform statistics as an APPEND-ONLY time series: every update inserts a
-- new row (never an upsert), so follower growth and other trends can be
-- computed from history. recorded_at orders the series.
CREATE TABLE platform_stats (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_kit_id BIGINT NOT NULL REFERENCES media_kits(id) ON DELETE CASCADE,
    platform     VARCHAR(20) NOT NULL,
    followers    BIGINT NOT NULL,
    avg_views    BIGINT,
    avg_likes    BIGINT,
    avg_comments BIGINT,
    recorded_at  TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_platform_stats_series
    ON platform_stats (media_kit_id, platform, recorded_at);

-- Audience distribution. One row per (category, label) with a percentage;
-- updates replace a kit's whole distribution (a distribution is not a series).
CREATE TABLE audience_demographics (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_kit_id BIGINT NOT NULL REFERENCES media_kits(id) ON DELETE CASCADE,
    category     VARCHAR(20) NOT NULL,
    label        VARCHAR(50) NOT NULL,
    percentage   NUMERIC(5,2) NOT NULL,
    UNIQUE (media_kit_id, category, label)
);

-- ---------------------------------------------------------------------------
-- Demo kit showcase data: current stats, a 35-day-old baseline per platform
-- (so the 30-day growth badge has something to compare against), demographics,
-- and a v2 snapshot so the public /demo page shows the full picture.
-- Engagement rates and growth below match what the calculators produce:
--   YouTube  (3600+240)/48000*100  = 8.00   growth (125000-112000)/112000 = 11.6
--   Instagram (5000+460)/84000*100 = 6.50   growth (84000-80000)/80000    = 5.0
--   TikTok  (12000+800)/95000*100  = 13.47  growth (210000-168000)/168000 = 25.0
-- ---------------------------------------------------------------------------
INSERT INTO platform_stats (media_kit_id, platform, followers, avg_views, avg_likes, avg_comments, recorded_at)
SELECT id, 'YOUTUBE', 112000, 45000, 3400, 220, CURRENT_TIMESTAMP - INTERVAL '35' DAY FROM media_kits WHERE slug = 'demo';
INSERT INTO platform_stats (media_kit_id, platform, followers, avg_views, avg_likes, avg_comments, recorded_at)
SELECT id, 'INSTAGRAM', 80000, NULL, 4700, 420, CURRENT_TIMESTAMP - INTERVAL '35' DAY FROM media_kits WHERE slug = 'demo';
INSERT INTO platform_stats (media_kit_id, platform, followers, avg_views, avg_likes, avg_comments, recorded_at)
SELECT id, 'TIKTOK', 168000, 78000, 9500, 650, CURRENT_TIMESTAMP - INTERVAL '35' DAY FROM media_kits WHERE slug = 'demo';

INSERT INTO platform_stats (media_kit_id, platform, followers, avg_views, avg_likes, avg_comments, recorded_at)
SELECT id, 'YOUTUBE', 125000, 48000, 3600, 240, CURRENT_TIMESTAMP FROM media_kits WHERE slug = 'demo';
INSERT INTO platform_stats (media_kit_id, platform, followers, avg_views, avg_likes, avg_comments, recorded_at)
SELECT id, 'INSTAGRAM', 84000, NULL, 5000, 460, CURRENT_TIMESTAMP FROM media_kits WHERE slug = 'demo';
INSERT INTO platform_stats (media_kit_id, platform, followers, avg_views, avg_likes, avg_comments, recorded_at)
SELECT id, 'TIKTOK', 210000, 95000, 12000, 800, CURRENT_TIMESTAMP FROM media_kits WHERE slug = 'demo';

INSERT INTO audience_demographics (media_kit_id, category, label, percentage)
SELECT id, 'AGE', '18-24', 38.0 FROM media_kits WHERE slug = 'demo';
INSERT INTO audience_demographics (media_kit_id, category, label, percentage)
SELECT id, 'AGE', '25-34', 41.0 FROM media_kits WHERE slug = 'demo';
INSERT INTO audience_demographics (media_kit_id, category, label, percentage)
SELECT id, 'AGE', '35-44', 14.0 FROM media_kits WHERE slug = 'demo';
INSERT INTO audience_demographics (media_kit_id, category, label, percentage)
SELECT id, 'AGE', '45+', 7.0 FROM media_kits WHERE slug = 'demo';
INSERT INTO audience_demographics (media_kit_id, category, label, percentage)
SELECT id, 'GENDER', 'Kadin', 58.0 FROM media_kits WHERE slug = 'demo';
INSERT INTO audience_demographics (media_kit_id, category, label, percentage)
SELECT id, 'GENDER', 'Erkek', 42.0 FROM media_kits WHERE slug = 'demo';
INSERT INTO audience_demographics (media_kit_id, category, label, percentage)
SELECT id, 'COUNTRY', 'Turkiye', 72.0 FROM media_kits WHERE slug = 'demo';
INSERT INTO audience_demographics (media_kit_id, category, label, percentage)
SELECT id, 'COUNTRY', 'Almanya', 11.0 FROM media_kits WHERE slug = 'demo';
INSERT INTO audience_demographics (media_kit_id, category, label, percentage)
SELECT id, 'COUNTRY', 'ABD', 6.0 FROM media_kits WHERE slug = 'demo';
INSERT INTO audience_demographics (media_kit_id, category, label, percentage)
SELECT id, 'COUNTRY', 'Diger', 11.0 FROM media_kits WHERE slug = 'demo';

-- Demo snapshot v2: same shape MediaKitSnapshot serializes to, stats included.
INSERT INTO media_kit_versions (media_kit_id, version_number, slug, content_json, published_at)
SELECT id, 2, 'demo',
       '{"slug":"demo","title":"Demo Medya Kiti","headline":"LocalMediaKit ile yayinlanan ornek medya kiti","avatarUrl":null,"theme":"light","displayName":"LocalMediaKit","platforms":[{"platform":"YOUTUBE","followers":125000,"avgViews":48000,"avgLikes":3600,"avgComments":240,"engagementRate":8.00,"followerGrowth30d":11.6},{"platform":"INSTAGRAM","followers":84000,"avgViews":null,"avgLikes":5000,"avgComments":460,"engagementRate":6.50,"followerGrowth30d":5.0},{"platform":"TIKTOK","followers":210000,"avgViews":95000,"avgLikes":12000,"avgComments":800,"engagementRate":13.47,"followerGrowth30d":25.0}],"demographics":[{"category":"AGE","label":"18-24","percentage":38.0},{"category":"AGE","label":"25-34","percentage":41.0},{"category":"AGE","label":"35-44","percentage":14.0},{"category":"AGE","label":"45+","percentage":7.0},{"category":"GENDER","label":"Kadin","percentage":58.0},{"category":"GENDER","label":"Erkek","percentage":42.0},{"category":"COUNTRY","label":"Turkiye","percentage":72.0},{"category":"COUNTRY","label":"Almanya","percentage":11.0},{"category":"COUNTRY","label":"ABD","percentage":6.0},{"category":"COUNTRY","label":"Diger","percentage":11.0}]}',
       CURRENT_TIMESTAMP
FROM media_kits WHERE slug = 'demo';

UPDATE media_kits
SET published_version_id = (SELECT id FROM media_kit_versions
                            WHERE slug = 'demo' AND version_number = 2)
WHERE slug = 'demo';
