-- Past brand collaborations: the social-proof showcase. display_order is the
-- owner-chosen showcase position; the public page shows them in that order,
-- frozen into the publish snapshot like stats and demographics.
CREATE TABLE brand_collaborations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_kit_id  BIGINT NOT NULL REFERENCES media_kits(id) ON DELETE CASCADE,
    brand_name    VARCHAR(255) NOT NULL,
    campaign      VARCHAR(500),
    period        VARCHAR(100),
    result_note   VARCHAR(1000),
    logo_url      VARCHAR(1000),
    display_order INT NOT NULL DEFAULT 0
);

CREATE INDEX idx_brand_collaborations_kit
    ON brand_collaborations (media_kit_id, display_order);

-- Demo showcase collaborations + a v3 snapshot so /demo shows the section.
INSERT INTO brand_collaborations (media_kit_id, brand_name, campaign, period, result_note, logo_url, display_order)
SELECT id, 'Kahve Diyari', 'Yeni urun lansmani', '2025 Q4', '1,2M goruntulenme, 8400 tiklama', NULL, 0
FROM media_kits WHERE slug = 'demo';
INSERT INTO brand_collaborations (media_kit_id, brand_name, campaign, period, result_note, logo_url, display_order)
SELECT id, 'TeknoMarket', 'Kulaklik incelemesi', '2025 Q3', 'Satis kodu ile 950 donusum', NULL, 1
FROM media_kits WHERE slug = 'demo';
INSERT INTO brand_collaborations (media_kit_id, brand_name, campaign, period, result_note, logo_url, display_order)
SELECT id, 'GezginApp', 'Seyahat vlog serisi', '2025 Q2', '3 video, toplam 2,1M izlenme', NULL, 2
FROM media_kits WHERE slug = 'demo';

INSERT INTO media_kit_versions (media_kit_id, version_number, slug, content_json, published_at)
SELECT id, 3, 'demo',
       '{"slug":"demo","title":"Demo Medya Kiti","headline":"LocalMediaKit ile yayinlanan ornek medya kiti","avatarUrl":null,"theme":"light","displayName":"LocalMediaKit","platforms":[{"platform":"YOUTUBE","followers":125000,"avgViews":48000,"avgLikes":3600,"avgComments":240,"engagementRate":8.00,"followerGrowth30d":11.6},{"platform":"INSTAGRAM","followers":84000,"avgViews":null,"avgLikes":5000,"avgComments":460,"engagementRate":6.50,"followerGrowth30d":5.0},{"platform":"TIKTOK","followers":210000,"avgViews":95000,"avgLikes":12000,"avgComments":800,"engagementRate":13.47,"followerGrowth30d":25.0}],"demographics":[{"category":"AGE","label":"18-24","percentage":38.0},{"category":"AGE","label":"25-34","percentage":41.0},{"category":"AGE","label":"35-44","percentage":14.0},{"category":"AGE","label":"45+","percentage":7.0},{"category":"GENDER","label":"Kadin","percentage":58.0},{"category":"GENDER","label":"Erkek","percentage":42.0},{"category":"COUNTRY","label":"Turkiye","percentage":72.0},{"category":"COUNTRY","label":"Almanya","percentage":11.0},{"category":"COUNTRY","label":"ABD","percentage":6.0},{"category":"COUNTRY","label":"Diger","percentage":11.0}],"collaborations":[{"brandName":"Kahve Diyari","campaign":"Yeni urun lansmani","period":"2025 Q4","resultNote":"1,2M goruntulenme, 8400 tiklama","logoUrl":null},{"brandName":"TeknoMarket","campaign":"Kulaklik incelemesi","period":"2025 Q3","resultNote":"Satis kodu ile 950 donusum","logoUrl":null},{"brandName":"GezginApp","campaign":"Seyahat vlog serisi","period":"2025 Q2","resultNote":"3 video, toplam 2,1M izlenme","logoUrl":null}]}',
       CURRENT_TIMESTAMP
FROM media_kits WHERE slug = 'demo';

UPDATE media_kits
SET published_version_id = (SELECT id FROM media_kit_versions
                            WHERE slug = 'demo' AND version_number = 3)
WHERE slug = 'demo';
