-- Visitor analytics as an append-only event series. One row per counted view;
-- dedup happens at ingestion time (30-minute visitor session window), so the
-- table only ever grows and aggregations stay simple.
-- visitor_hash is an anonymous daily-rotating fingerprint (sha256 of
-- ip|user-agent|day|salt) - the raw IP is never stored.
CREATE TABLE page_views (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_kit_id BIGINT NOT NULL REFERENCES media_kits(id) ON DELETE CASCADE,
    slug         VARCHAR(255) NOT NULL,
    visitor_hash VARCHAR(64) NOT NULL,
    referrer     VARCHAR(500),
    device       VARCHAR(20),
    viewed_at    TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_page_views_kit_time ON page_views (media_kit_id, viewed_at);
CREATE INDEX idx_page_views_dedup ON page_views (media_kit_id, visitor_hash, viewed_at);
