-- Billing state (Stripe TEST MODE - no real money ever moves).
-- One subscription row per user; the row survives cancellation as history.
CREATE TABLE subscriptions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT NOT NULL UNIQUE REFERENCES users(id),
    stripe_customer_id     VARCHAR(255),
    stripe_subscription_id VARCHAR(255) UNIQUE,
    status                 VARCHAR(30) NOT NULL,
    current_period_end     TIMESTAMP(6),
    created_at             TIMESTAMP(6) NOT NULL,
    updated_at             TIMESTAMP(6) NOT NULL
);

-- Webhook idempotency: Stripe retries deliveries, so every event id is
-- recorded in the SAME transaction that applies its effects. A duplicate
-- delivery finds the id here and is swallowed.
CREATE TABLE processed_stripe_events (
    event_id    VARCHAR(255) PRIMARY KEY,
    received_at TIMESTAMP(6) NOT NULL
);
